<?php
include '../../Models/process.php';
require_role('admin');
$conn=connect();
$produk=mysqli_query($conn,"SELECT * FROM produk WHERE penjual_id=".(int)$_SESSION['id']." ORDER BY id DESC");
$pesanan=mysqli_query($conn,"SELECT pesanan.*, pengguna.username AS pembeli FROM pesanan JOIN pengguna ON pesanan.pembeli_id=pengguna.id WHERE pesanan.penjual_id=".(int)$_SESSION['id']." ORDER BY pesanan.id DESC");
$status=cek_data_get('status');
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smartpo - Penjual</title>
<style>*{box-sizing:border-box;margin:0;padding:0;font-family:Arial,sans-serif}body{background:#f1fff5;color:#234d30;padding:30px}.wrap{max-width:1000px;margin:auto}.head,.box{background:#fff;padding:25px;border-radius:18px;box-shadow:0 8px 25px #0001;margin-bottom:22px}.head{border-left:7px solid #43a047}.head h1{color:#236b38}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.group{margin-bottom:16px}.group label{display:block;font-weight:bold;margin-bottom:7px}.group input,.group textarea{width:100%;padding:12px;border:1px solid #cfe5d5;border-radius:10px}.group textarea{min-height:90px}.submit,.logout{border:0;background:#43a047;color:#fff;padding:12px 18px;border-radius:10px;font-weight:bold;cursor:pointer}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #ddd;text-align:left}.tag{padding:4px 8px;background:#e1f6e7;border-radius:8px}.topline{display:flex;justify-content:space-between;align-items:center;gap:15px}.logout{background:#e53935;text-decoration:none;display:inline-block}.msg{padding:12px;background:#e5f8e9;border-radius:10px;margin-bottom:18px}@media(max-width:750px){.grid{grid-template-columns:1fr}.table{font-size:13px}}
</style></head><body><div class="wrap">
<div class="head"><div class="topline"><div><h1>🛍️ Smartpo - Dashboard Penjual</h1><p>Kelola produk, stok, minimal waktu antar, dan pesanan.</p></div><a class="logout" href="../../Controllers/logout.php">Logout</a></div></div>
<?php if($status==='produk'): ?><div class="msg">Produk berhasil ditambahkan.</div><?php endif; ?>
<div class="box"><h2>Tambah Produk</h2><br><form method="post" action="../../Models/process.php"><div class="grid"><div><div class="group"><label>Nama Produk</label><input name="nama_produk" required></div><div class="group"><label>Harga</label><input type="number" name="harga" min="0" required></div><div class="group"><label>Stok</label><input type="number" name="stock" min="0" required></div></div><div><div class="group"><label>Minimal Hari Antar</label><input type="number" name="minimal_hari" min="0" required><small>Contoh: 7 berarti pembeli harus memilih tanggal antar minimal 7 hari dari hari ini.</small></div><div class="group"><label>Lokasi Penjual</label><input name="lokasi" placeholder="Contoh: Kelas XII PPLG 2" required></div><div class="group"><label>Deskripsi</label><textarea name="deskripsi"></textarea></div></div></div><input type="submit" name="dor" value="Tambah Produk" class="submit"></form></div>
<div class="box"><h2>Produk Saya</h2><br><table class="table"><tr><th>Produk</th><th>Harga</th><th>Stok</th><th>Minimal Antar</th><th>Lokasi</th></tr><?php while($p=mysqli_fetch_assoc($produk)): ?><tr><td><?=e($p['nama_produk'])?></td><td>Rp <?=number_format($p['harga'],0,',','.')?></td><td><?=e($p['stock'])?></td><td><?=e($p['minimal_hari'])?> hari</td><td><?=e($p['lokasi'])?></td></tr><?php endwhile; ?></table></div>
<div class="box"><h2>Pesanan Masuk</h2><br><table class="table"><tr><th>Pembeli</th><th>Produk</th><th>Total</th><th>Tanggal Antar</th><th>Status</th></tr><?php while($o=mysqli_fetch_assoc($pesanan)): $items=json_decode($o['detail_produk'],true); ?><tr><td><?=e($o['pembeli'])?></td><td><?php foreach($items as $item) echo e($item['nama']).' x'.(int)$item['jumlah'].'<br>'; ?></td><td>Rp <?=number_format($o['total'],0,',','.')?></td><td><?=e($o['tanggal_antar'])?></td><td><span class="tag"><?=e($o['status'])?></span></td></tr><?php endwhile; ?></table></div>
</div></body></html>
