<?php
include '../../Models/process.php';
require_role('user');
$conn=connect();
$produk=mysqli_query($conn,"SELECT produk.*, pengguna.username AS penjual FROM produk JOIN pengguna ON produk.penjual_id=pengguna.id WHERE produk.stock>0 ORDER BY pengguna.username, produk.id DESC");
$group=[]; while($p=mysqli_fetch_assoc($produk)) $group[$p['penjual_id']][]=$p;
$status=cek_data_get('status');
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smartpo - Pembeli</title>
<style>*{box-sizing:border-box;margin:0;padding:0;font-family:Arial,sans-serif}body{background:#f4fff7;color:#214c30;padding:30px}.wrap{max-width:1100px;margin:auto}.head,.seller{background:#fff;border-radius:18px;box-shadow:0 8px 25px #0001;padding:25px;margin-bottom:22px}.head{border-left:7px solid #43a047}.top{display:flex;justify-content:space-between;align-items:center}.logout{background:#e53935;color:#fff;text-decoration:none;padding:10px 15px;border-radius:9px}.msg{padding:12px;background:#e4f7e9;border-radius:10px;margin-bottom:18px}.seller h2{color:#287340}.seller-info{color:#63776a;margin:6px 0 18px}.products{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.product{border:1px solid #d9e9dc;border-radius:12px;padding:15px}.product h3{margin-bottom:6px}.price{font-weight:bold;color:#2e8b57}.qty{margin-top:10px;width:90px;padding:8px;border:1px solid #ccc;border-radius:8px}.orderbar{margin-top:18px;padding-top:18px;border-top:1px solid #ddd;display:flex;gap:15px;align-items:end;flex-wrap:wrap}.orderbar label{display:block;font-weight:bold;margin-bottom:6px}.orderbar input[type=date]{padding:10px;border:1px solid #ccc;border-radius:8px}.submit{padding:11px 18px;background:#43a047;color:#fff;border:0;border-radius:9px;font-weight:bold;cursor:pointer}@media(max-width:750px){.products{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="head"><div class="top"><div><h1>🛒 Smartpo - Dashboard Pembeli</h1><p>Halo, <?=e($_SESSION['sesi'])?>. Pilih produk dari satu penjual untuk satu pesanan.</p></div><a class="logout" href="../../Controllers/logout.php">Logout</a></div></div>
<?php if($status==='pesan'): ?><div class="msg">Pesanan berhasil dibuat dan stok produk otomatis berkurang.</div><?php elseif($status==='stock'): ?><div class="msg">Stok salah satu produk tidak mencukupi.</div><?php elseif($status==='min'): ?><div class="msg">Tanggal antar harus minimal <?=e(cek_data_get('hari'))?> hari dari hari ini.</div><?php elseif($status==='kosong'): ?><div class="msg">Pilih minimal satu produk.</div><?php elseif($status==='gagal'): ?><div class="msg">Pesanan gagal dibuat. Silakan coba lagi.</div><?php endif; ?>
<?php foreach($group as $sellerId=>$items): $sellerName=$items[0]['penjual']; $maxMin=0; foreach($items as $p) $maxMin=max($maxMin,(int)$p['minimal_hari']); $minDate=date('Y-m-d',strtotime('+'.$maxMin.' days')); ?>
<div class="seller"><h2>Penjual: <?=e($sellerName)?></h2><div class="seller-info">Dalam satu pesanan, produk hanya boleh berasal dari penjual ini.</div><form method="post" action="../../Models/process.php"><input type="hidden" name="penjual_id" value="<?=e($sellerId)?>"><div class="products"><?php foreach($items as $p): ?><div class="product"><h3><?=e($p['nama_produk'])?></h3><div class="price">Rp <?=number_format($p['harga'],0,',','.')?></div><p>Stok: <?=e($p['stock'])?></p><p>Minimal antar: <?=e($p['minimal_hari'])?> hari</p><p>Lokasi: <?=e($p['lokasi'])?></p><input class="qty" type="number" name="jumlah[<?=e($p['id'])?>]" min="0" max="<?=e($p['stock'])?>" value="0"></div><?php endforeach; ?></div><div class="orderbar"><div><label>Tanggal Antar</label><input type="date" name="tanggal_antar" min="<?=$minDate?>" required></div><button class="submit" name="dor" value="Buat Pesanan">Pesan dari <?=e($sellerName)?></button></div></form></div>
<?php endforeach; if(empty($group)): ?><div class="seller"><h3>Belum ada produk yang tersedia.</h3></div><?php endif; ?></div></body></html>
